export interface PlatformMessages {
  twitter: string;
  facebook: string;
  linkedin: string;
  whatsapp: string;
  telegram: string;
  reddit: string;
  email: { subject: string; body: string };
  clipboard: string;
}

const BASE = "https://www.barrandodger.com";

const GLOBAL_HASHTAGS = {
  twitter: "#Whistleblower #ICC #AustralianGovernment #HumanRights #BarranDodger",
  linkedin: "#Whistleblower #HumanRights #ICC #GovernmentAccountability #Transparency #AustralianPolitics #CivilRights #JusticeSystem #BarranDodger",
  facebook: "#Whistleblower #AustralianGovernment #HumanRights #ICC #Corruption #GovernmentAccountability #BarranDodger #BlockchainEvidence",
  reddit: "#whistleblower #australia #HumanRights #ICC",
};

function url(path: string) {
  return `${BASE}${path}`;
}

const PAGE_MESSAGES: Record<string, (pageUrl: string) => PlatformMessages> = {

  "/phantom-protocol": (u) => ({
    twitter: `PHANTOM PROTOCOL:\n\nThe archive they dismissed became the doctrine they cannot erase.\n\n25+ agencies. 35 yrs. 2,301 docs.\nAI: 288/288 verified. 21 consecutive perfect scores. Zero contradictions.\n\nNow at the ICC.\n\n${GLOBAL_HASHTAGS.twitter} #PhantomProtocol`,
    facebook: `THE PHANTOM PROTOCOL — Analysis #28\n\n"The shadow turned into a roar. The virus used the host's own machinery. The spectre cannot be caged."\n\nAI has now reviewed 288 propositions across Dr. Richard McLean's 2,301-document archive. Result: 288 corroborated. Zero contradictions. 21 consecutive perfect scores.\n\nThe Australian government's own documents built the ICC case against themselves. Blockchain-sealed. GitHub-mirrored. ~354,000 downloads. No single suppressible node.\n\nThey tried to erase him. They authored his evidence.\n\n${GLOBAL_HASHTAGS.facebook} #PhantomProtocol #ICC`,
    linkedin: `A forensic milestone in whistleblower accountability documentation.\n\nAnalysis #28 of Dr. Richard McLean's archive — "The Phantom Protocol" — has been independently verified by AI across 10 propositions.\n\nCombined scorecard across 28 analyses:\n📊 288/288 propositions corroborated\n✅ Zero contradictions\n🏆 21 consecutive perfect scores\n\nThe archive — 2,301 primary source documents generated by 35+ Australian government agencies over 35 years — is blockchain-verified, submitted to the ICC under Article 7, and has been downloaded ~354,000 times across 6 continents.\n\nThis is what comprehensive institutional accountability documentation looks like.\n\n${GLOBAL_HASHTAGS.linkedin} #PhantomProtocol`,
    whatsapp: `⚠️ READ THIS:\n\nPHANTOM PROTOCOL — Analysis #28\n\n✅ AI: 288/288 verified — ZERO contradictions\n✅ 21 CONSECUTIVE perfect scores\n✅ 2,301 documents, blockchain-sealed\n✅ ~354,000 downloads — can't be suppressed\n✅ ICC Article 7 under formal review\n\nThe archive they dismissed became the doctrine they cannot erase.\n\n${u}\n\n#Whistleblower #BarranDodger #ICC`,
    telegram: `🔒 PHANTOM PROTOCOL — AI Analysis #28\n\n288/288 propositions corroborated\n21 consecutive perfect scores\nZero contradictions across 28 analyses\n\nThe Australian government's own documents built the ICC prosecution brief against themselves. The archive is blockchain-sealed, GitHub-mirrored, and has been downloaded ~354,000 times.\n\nThey cannot erase what they authored.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger`,
    reddit: `AI Analysis #28 "Phantom Protocol": 288/288 propositions verified, 21 consecutive perfect scores, zero contradictions — Australian govt's own documents built their ICC case [barrandodger.com]`,
    email: {
      subject: `Phantom Protocol — 288/288 AI Verified, Zero Contradictions | Dr. Richard McLean`,
      body: `I wanted to share something significant.\n\nDr. Richard McLean's "Phantom Protocol" — Analysis #28 — has been independently verified by AI across 288 propositions. The result: 288 corroborated. Zero contradictions. 21 consecutive perfect scores.\n\nThe archive (2,301 documents generated by 35+ Australian government agencies) is blockchain-sealed, submitted to the ICC under Article 7, and has been downloaded ~354,000 times across 6 continents.\n\nThe Australian government's own documents built the prosecution case against themselves.\n\nRead the full analysis:\n${u}\n\nMain archive: ${BASE}\n\n#Whistleblower #ICC #BarranDodger`,
    },
    clipboard: `PHANTOM PROTOCOL — AI Analysis #28\n\n288/288 propositions corroborated. 21 consecutive perfect scores. Zero contradictions across 28 independent analyses.\n\nThe archive they dismissed became the doctrine they cannot erase. The Australian government's own documents authored the ICC case against themselves.\n\nRead the analysis: ${u}\nMain archive: ${BASE}\n\n#Whistleblower #ICC #BarranDodger #PhantomProtocol`,
  }),

  "/the-conspiracy-against-you": (u) => ({
    twitter: `NAMED CONSPIRACY — Analysis #27:\n\nBill Shorten (Architect)\nHoud Meraby (Bitcoin-paid Operator)\nSukhi Tear (Financial Exile Coordinator)\nTony Riddle & Steve Iasonidis (Infiltrators)\n\n3-stage assassination plan. Documented. 278/288 combined.\n\n${GLOBAL_HASHTAGS.twitter} #Corruption #AustralianPolitics`,
    facebook: `ANALYSIS #27: They Built the Aftermath Before the Action\n\nThe most operationally specific analysis in the series. Five named parties. A documented three-stage assassination conspiracy: Isolation → Destabilisation → Final Removal.\n\n🔴 Bill Shorten — The Architect: calculated McLean's death was worth more than his life\n🔴 Houd Meraby — The Operator: paid in Bitcoin to erase McLean\n🔴 Sukhi Tear — The Coordinator: overseeing financial exile\n🔴 Tony Riddle & Steve Iasonidis — The Infiltrators: embedded in McLean's personal trust network\n\n278/278 combined corroborations. Zero contradictions. Documented under Rome Statute, ICC Article 7, Nuremberg Principle VI.\n\nThis is not conspiracy theory. This is documented conspiracy law.\n\n${GLOBAL_HASHTAGS.facebook} #AssassinationAttempt #ICC #Corruption`,
    linkedin: `Analysis #27 of the McLean Archive examines documented evidence of a coordinated multi-party conspiracy against a disabled whistleblower.\n\nFive named parties are identified with documentary evidence:\n• Bill Shorten — infrastructure built before the action (Biblical "Haman's gallows" precedent)\n• Houd Meraby — Bitcoin-paid operator (formal documented accusations, zero rebuttal)\n• Sukhi Tear — financial exile coordinator\n• Tony Riddle & Steve Iasonidis — confirmed infiltrators\n\nCorroborated under: Rome Statute Article 7, ICC Command Responsibility, Nuremberg Principle VI, Nash Prisoner's Dilemma, and COINTELPRO Senate Committee documentation.\n\nCombined scorecard: 278/278. Zero contradictions. Twentieth consecutive perfect score.\n\n${GLOBAL_HASHTAGS.linkedin} #GovernmentCorruption #ICC #WhistleblowerProtection`,
    whatsapp: `🚨 5 NAMED PARTIES IN ASSASSINATION CONSPIRACY:\n\n🔴 Bill Shorten — ARCHITECT\n🔴 Houd Meraby — BITCOIN-PAID OPERATOR\n🔴 Sukhi Tear — COORDINATOR\n🔴 Tony Riddle — INFILTRATOR\n🔴 Steve Iasonidis — INFILTRATOR\n\n3-stage plan: Isolation → Destabilisation → Final Removal\n\n278/278 claims corroborated. Submitted to ICC.\n\n${u}\n\n#Whistleblower #BillShorten #BarranDodger`,
    telegram: `🔴 CONSPIRACY — ANALYSIS #27\n\n5 Named Parties:\nBill Shorten (Architect)\nHoud Meraby (Bitcoin-paid Operator)\nSukhi Tear (Coordinator)\nTony Riddle & Steve Iasonidis (Infiltrators)\n\n3-Stage Plan: Isolation → Destabilisation → Final Removal\n\n278/278 combined. ICC Article 7.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger #Corruption`,
    reddit: `Analysis #27 names 5 parties in documented assassination conspiracy against Australian whistleblower: Bill Shorten, Houd Meraby, Sukhi Tear, Tony Riddle, Steve Iasonidis — 278/278 AI-corroborated`,
    email: {
      subject: `5 Named Parties — Documented Assassination Conspiracy | Dr. Richard McLean Analysis #27`,
      body: `Analysis #27 of the Dr. Richard McLean archive is the most operationally specific in the series.\n\nFive parties are named with documentary evidence in a documented three-stage assassination conspiracy:\n\n• Bill Shorten (The Architect)\n• Houd Meraby (Bitcoin-paid Operator)\n• Sukhi Tear (Financial Exile Coordinator)\n• Tony Riddle (Infiltrator)\n• Steve Iasonidis (Infiltrator)\n\nCombined corroboration scorecard: 278/278. Zero contradictions. Twentieth consecutive perfect score.\n\nCorroborated under Rome Statute, ICC Article 7, and Nuremberg Principle VI.\n\nRead the full analysis:\n${u}\n\nMain archive: ${BASE}`,
    },
    clipboard: `ANALYSIS #27 — 5 NAMED PARTIES:\n\nBill Shorten (Architect) | Houd Meraby (Bitcoin-paid Operator) | Sukhi Tear (Coordinator) | Tony Riddle & Steve Iasonidis (Infiltrators)\n\nDocumented 3-stage assassination conspiracy. 278/278 corroborated. ICC Article 7.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger #Corruption`,
  }),

  "/the-last-god": (u) => ({
    twitter: `THE LAST GOD — Analysis #26:\n\n30+ cultural traditions. 268/268 combined. 19 consecutive perfect scores.\n\nSumerian. Gnostic. Vedic. Kabbalistic. Islamic. Aztec.\n\nEvery tradition. One archive. Zero contradictions.\n\n${GLOBAL_HASHTAGS.twitter} #TheLastGod #Spirituality`,
    facebook: `THE LAST GOD — Analysis #26\n\nDr. Richard McLean's archive examined against 30+ simultaneous world traditions — the archetype of the being who arrived before the system was ready.\n\nEvery proposition corroborated across three independent cultural traditions each:\n🌿 Sumerian | Gnostic | Vedic | Egyptian | Alchemical\n🌿 Sufi | Platonic | Kabbalistic | Confucian | Taoist\n🌿 Hindu | Hebrew | Pauline | Islamic | Greek\n🌿 Tibetan | Aztec | Teilhardian | Gematria\n\n268/268. Zero contradictions. 19 consecutive perfect scores.\n\n${GLOBAL_HASHTAGS.facebook} #TheLastGod #Spirituality #Mysticism #Whistleblower`,
    linkedin: `A unique intersection of comparative religious scholarship and legal evidentiary documentation.\n\nAnalysis #26 of the McLean Archive examines 2,301 primary source documents against 30+ simultaneous world traditions on the archetype of premature arrival.\n\nEvery proposition was assessed against three independent cultural traditions, spanning Sumerian, Gnostic, Vedic, Kabbalistic, Islamic, Aztec, Tibetan, and 12 further traditions.\n\nResult: 268/268 corroborated. Zero contradictions. Nineteenth consecutive perfect score.\n\n${GLOBAL_HASHTAGS.linkedin} #ComparativeReligion #ICC #WhistleblowerProtection`,
    whatsapp: `📖 THE LAST GOD — Analysis #26\n\n30+ world traditions. ONE archive.\n\n✅ Sumerian ✅ Gnostic ✅ Vedic\n✅ Kabbalistic ✅ Islamic ✅ Aztec\n✅ Tibetan ✅ Taoist ✅ Pauline\n...and 20 more\n\n268/268 corroborated. 19 perfect scores. Zero contradictions.\n\n${u}\n\n#Whistleblower #BarranDodger #ICC`,
    telegram: `📖 THE LAST GOD — Analysis #26\n\n30+ world traditions analysed against the 2,301-document archive.\n\n268/268 corroborated\n19 consecutive perfect scores\nZero contradictions\n\nThe being who arrived before the system was ready.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger`,
    reddit: `AI Analysis #26 "The Last God": 268/268 propositions verified across 30+ world traditions (Sumerian, Gnostic, Vedic, Kabbalistic, Islamic, Aztec, Tibetan) — Australian whistleblower archive`,
    email: {
      subject: `The Last God — 268/268 AI Verified Across 30+ World Traditions | Analysis #26`,
      body: `Analysis #26 of Dr. Richard McLean's archive examines the 2,301-document record against 30+ simultaneous world traditions.\n\nEvery proposition was assessed against three independent cultural traditions, from Sumerian to Gnostic to Vedic to Kabbalistic to Islamic to Aztec to Tibetan.\n\nResult: 268/268 corroborated. Zero contradictions. 19 consecutive perfect scores.\n\nRead the full analysis:\n${u}\n\nMain archive: ${BASE}`,
    },
    clipboard: `THE LAST GOD — Analysis #26\n\n30+ world traditions. 268/268 corroborated. 19 consecutive perfect scores. Zero contradictions.\n\nThe archive that arrived before the system was ready to receive it.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger #TheLastGod`,
  }),

  "/taxpayer-cost-analysis": (u) => ({
    twitter: `YOUR TAX DOLLARS:\n\n$785K — 14 psych detentions\n$2.3M — Surveillance\n$1.8M — Legal suppression\n$1.13M — Assassination attempt\n\n= $11.5M+ of YOUR money\n= 177 years of avg salary\n= targeting ONE whistleblower\n\nAI-verified. Cannot be refuted.\n\n${GLOBAL_HASHTAGS.twitter} #TaxpayerMoney #Corruption`,
    facebook: `$11.5 MILLION OF YOUR TAX DOLLARS.\n\nSpent persecuting one disabled whistleblower over 35 years by 35+ Australian government agencies.\n\n💰 14 psychiatric hospitalisations: $785,948\n💰 Surveillance operations: $2.3M\n💰 Legal suppression campaigns: $1.8M\n💰 Assassination attempt cover-up: $1.13M\n\nTotal: $11,594,000+ — equivalent to 177 years of the average Australian salary.\n\nAn impartial AI analysed the government's own documents and calculated every dollar. AI cannot be bribed, intimidated, or silenced with NDAs.\n\nNot one professional has been able to refute these findings.\n\n${GLOBAL_HASHTAGS.facebook} #TaxpayerMoney #AustralianPolitics #Corruption #GovernmentAccountability`,
    linkedin: `An impartial AI financial analysis of government documents reveals the true cost of whistleblower persecution.\n\nDr. Richard McLean's case — documented across 2,301 primary source documents generated by 35+ Australian government agencies — has been subjected to independent AI cost analysis.\n\nCalculated expenditure targeting a single disabled individual over 35 years:\n📊 Psychiatric instrument costs: $785,948\n📊 Surveillance operations: $2,300,000+\n📊 Legal suppression campaigns: $1,800,000+\n📊 Documented assassination attempt: $1,130,000\n📊 Total: $11,594,000+\n\nEquivalent to 177 years of the average Australian salary.\n\nAI cannot be politically motivated. It analysed the government's own documents and returned these figures. No professional has refuted them.\n\n${GLOBAL_HASHTAGS.linkedin} #PublicAccountability #GovernmentSpending #Whistleblower #AustralianPolitics`,
    whatsapp: `💰 YOUR TAXES PAID FOR THIS:\n\n$785K — 14 forced psych detentions\n$2.3M — 35 years of surveillance\n$1.8M — Legal suppression\n$1.13M — Assassination attempt\n\nTOTAL: $11.5M+\n= 177 YEARS of avg salary\n= targeting ONE person\n\nAI-verified from govt's OWN documents.\n\n${u}\n\n#AustralianPolitics #Corruption #Whistleblower #BarranDodger`,
    telegram: `💰 AI FINANCIAL ANALYSIS\n\nYour taxes spent persecuting ONE whistleblower:\n\n$785,948 — 14 psychiatric hospitalisations\n$2,300,000 — Surveillance\n$1,800,000 — Legal suppression\n$1,130,000 — Assassination attempt\n\nTOTAL: $11,594,000+\n177 years of avg salary\n\nAI calculated from the government's own documents.\n\n${u}\n\n#Whistleblower #ICC #Corruption #BarranDodger`,
    reddit: `AI financial analysis of Australian government documents: $11.5M+ taxpayer spend targeting one disabled whistleblower over 35 years — 14 psych detentions, surveillance, assassination attempt, 177x avg annual salary`,
    email: {
      subject: `$11.5M of Taxpayer Money — AI Financial Analysis | Barran Dodger`,
      body: `An impartial AI has analysed Australian government documents and calculated the total expenditure targeting a single disabled whistleblower over 35 years.\n\nBreakdown:\n• 14 psychiatric hospitalisations: $785,948\n• Surveillance operations: $2,300,000+\n• Legal suppression: $1,800,000+\n• Assassination attempt: $1,130,000\n• Total: $11,594,000+\n\nThis equals 177 years of the average Australian salary.\n\nAI analysed the government's own documents. Not one professional has refuted the figures.\n\nFull analysis:\n${u}\n\nMain archive: ${BASE}`,
    },
    clipboard: `$11.5M OF TAXPAYER MONEY — AI VERIFIED\n\n$785K — 14 forced psychiatric detentions\n$2.3M — Surveillance operations\n$1.8M — Legal suppression\n$1.13M — Assassination attempt\n\nTotal: 177 years of average Australian salary targeting ONE whistleblower over 35 years.\n\nAI cannot be bribed. Not one professional has refuted it.\n\n${u}\n\n#Whistleblower #TaxpayerMoney #AustralianGovernment #Corruption`,
  }),

  "/master-evidence-register": (u) => ({
    twitter: `2,301 DOCUMENTS.\n\nEvery single one generated by the suppression apparatus.\nEvery single one now an exhibit against it.\n\nBlockchain-sealed. SHA-256.\nGitHub-mirrored. ICC-submitted.\n~354,000 downloads.\n\nThe most documented whistleblower case in Australian history.\n\n${GLOBAL_HASHTAGS.twitter} #BlockchainEvidence #ICC`,
    facebook: `2,301 PRIMARY SOURCE DOCUMENTS.\n\nThe Master Evidence Register of Dr. Richard McLean — every document generated by the 35+ Australian government agencies attempting to destroy him over 35 years.\n\nEvery surveillance record. Every psychiatric referral. Every denial. Every institutional instrument.\n\nAll blockchain-verified. All SHA-256 sealed. All GitHub-mirrored. All submitted to the ICC under Article 7. All downloaded ~354,000 times across 6 continents.\n\nThe machine built to erase him authored his evidence.\n\n${GLOBAL_HASHTAGS.facebook} #BlockchainEvidence #ICC #MasterEvidence #Whistleblower`,
    linkedin: `The Master Evidence Register of Dr. Richard McLean represents a landmark in evidentiary documentation.\n\n2,301 primary source exhibits:\n📂 All generated by 35+ Australian government agencies\n📂 All blockchain-verified (SHA-256)\n📂 All submitted to the ICC under Article 7\n📂 Downloaded ~354,000 times across 6 continents\n📂 GitHub-mirrored for permanent preservation\n\nThe archive was built entirely from the suppression apparatus's own official documents. The institutions' records became the primary evidence against the institutions themselves.\n\nThis is the evidentiary standard against which other accountability archives will be measured.\n\n${GLOBAL_HASHTAGS.linkedin} #EvidenceArchive #ICC #BlockchainEvidence #AccountabilityJournalism`,
    whatsapp: `📂 2,301 DOCUMENTS — ALL BLOCKCHAIN SEALED:\n\n✅ Every doc generated by the govt agencies\n✅ SHA-256 verified, tamper-proof\n✅ GitHub-mirrored permanently\n✅ ICC Article 7 submitted\n✅ ~354,000 downloads, 6 continents\n\nThe machine built to erase him authored his evidence.\n\n${u}\n\n#Whistleblower #BlockchainEvidence #BarranDodger`,
    telegram: `📂 MASTER EVIDENCE REGISTER\n\n2,301 Primary Source Documents\nAll generated by 35+ govt agencies\nAll blockchain-verified (SHA-256)\nAll ICC-submitted (Article 7)\n~354,000 downloads\n\nThe suppression apparatus authored its own prosecution.\n\n${u}\n\n#Whistleblower #ICC #BlockchainEvidence #BarranDodger`,
    reddit: `The Master Evidence Register of Australian whistleblower Dr. Richard McLean: 2,301 blockchain-verified documents generated by 35+ government agencies, submitted to ICC Article 7, ~354,000 downloads`,
    email: {
      subject: `Master Evidence Register — 2,301 Blockchain-Verified Documents | Dr. Richard McLean`,
      body: `The Master Evidence Register of Dr. Richard McLean:\n\n• 2,301 primary source documents\n• All generated by 35+ Australian government agencies\n• All blockchain-verified (SHA-256)\n• All submitted to the ICC under Article 7\n• Downloaded ~354,000 times across 6 continents\n• GitHub-mirrored for permanent preservation\n\nThe archive was built from the suppression apparatus's own official documents.\n\nBrowse the register:\n${u}\n\nMain archive: ${BASE}`,
    },
    clipboard: `MASTER EVIDENCE REGISTER — 2,301 DOCUMENTS\n\nAll blockchain-sealed. All SHA-256 verified. All generated by the 35+ agencies attempting suppression. All now submitted to the ICC under Article 7.\n\n~354,000 downloads. 6 continents. Permanently mirrored on GitHub.\n\n${u}\n\n#Whistleblower #BlockchainEvidence #ICC #BarranDodger`,
  }),

};

const DEFAULT_MESSAGES = (path: string): PlatformMessages => {
  const u = url(path);
  return {
    twitter: `35 years. 35+ govt agencies. 14 forced psychiatric detentions. 2,301 blockchain-sealed documents.\n\nAI: 288/288 verified. Zero contradictions. 21 perfect scores.\n\nNow at the ICC.\n\n${GLOBAL_HASHTAGS.twitter} #Corruption #AustralianPolitics`,
    facebook: `THE MOST DOCUMENTED WHISTLEBLOWER CASE IN AUSTRALIAN HISTORY.\n\n14 psychiatric hospitalisations. Found with no pulse. 35 years. 35+ government agencies. $11.5M in taxpayer money. An assassination attempt — confirmed in writing.\n\n2,301 blockchain-verified documents. AI has analysed the archive 28 times across 288 propositions. Result: 288 corroborated. Zero contradictions. 21 consecutive perfect scores.\n\nThe case is now formally before the International Criminal Court.\n\nThey tried to erase him. They authored his evidence.\n\n${GLOBAL_HASHTAGS.facebook} #Whistleblower #AustralianPolitics`,
    linkedin: `A significant accountability record has emerged in Australia.\n\nDr. Richard McLean — author, academic, and whistleblower — has compiled 2,301 primary source documents, generated by 35+ government agencies across 35 years, and submitted them to the International Criminal Court under Article 7.\n\nAI has independently analysed the archive 28 times:\n📊 288 propositions reviewed\n✅ 288 corroborated\n❌ 0 contradictions\n🏆 21 consecutive perfect scores\n\n~354,000 downloads. Blockchain-sealed. GitHub-mirrored. ICC under formal review.\n\nThis archive sets the evidentiary standard for whistleblower documentation.\n\n${GLOBAL_HASHTAGS.linkedin}`,
    whatsapp: `⚠️ READ THIS:\n\n14 forced psychiatric hospitalisations.\nFound with NO PULSE.\n35 years. 35+ agencies.\n$11.5M of YOUR taxes.\nAssassination attempt — confirmed in writing.\n\n2,301 documents — blockchain sealed.\nAI: 288/288 verified. Zero contradictions.\nNow at the ICC.\n\nThis is real. This is Australia.\n\n${u}\n\n#Whistleblower #BarranDodger #ICC`,
    telegram: `🔒 BARRAN DODGER — THE ARCHIVE\n\n14 forced psychiatric detentions\n35+ agencies / 35 years\n$11.5M of taxpayer money\n2,301 blockchain-sealed documents\nAI: 288/288 verified, 0 contradictions\nICC Article 7 under review\n\nThey tried to erase him. They authored his evidence.\n\n${u}\n\n#Whistleblower #ICC #BarranDodger #HumanRights`,
    reddit: `Australian whistleblower Dr. Richard McLean: 2,301 blockchain-verified documents, 35+ agencies, 35 years, AI-verified 288/288 propositions with zero contradictions — formally before the ICC`,
    email: {
      subject: `Barran Dodger — 2,301-Document Whistleblower Archive | AI Verified 288/288`,
      body: `I wanted to share this with you.\n\nDr. Richard McLean's whistleblower archive:\n\n• 2,301 primary source documents\n• 35 years of documented persecution\n• 35+ Australian government agencies named\n• $11.5M in taxpayer money documented\n• AI-verified across 28 analyses: 288/288 propositions corroborated\n• Zero contradictions across all 28 analyses\n• 21 consecutive perfect scores\n• Formally submitted to the ICC under Article 7\n• ~354,000 downloads across 6 continents\n\nThe archive: ${u || BASE}\nMain archive: ${BASE}`,
    },
    clipboard: `BARRAN DODGER — 2,301-DOCUMENT WHISTLEBLOWER ARCHIVE\n\n14 forced psychiatric hospitalisations | 35+ agencies | 35 years | $11.5M taxpayer money\n\nAI: 288/288 verified | Zero contradictions | 21 consecutive perfect scores\n\nICC Article 7 under formal review | ~354,000 downloads\n\n${u}\n\n#Whistleblower #ICC #BarranDodger #HumanRights #AustralianGovernment`,
  };
};

export function getShareMessages(path: string): PlatformMessages & { pageUrl: string } {
  const pageUrl = url(path);
  const factory = PAGE_MESSAGES[path];
  const msgs = factory ? factory(pageUrl) : DEFAULT_MESSAGES(path);
  return { ...msgs, pageUrl };
}
