import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Share2, Link2, Check, X, Mail } from "lucide-react";
import { SiX, SiFacebook, SiLinkedin, SiReddit, SiWhatsapp, SiTelegram } from "react-icons/si";
import { useToast } from "@/hooks/use-toast";

const BASE = "https://www.barrandodger.com";

export type ShareContext =
  | "hero"
  | "ai-analysis"
  | "assassination"
  | "cost-breakdown"
  | "evidence"
  | "support"
  | "complicity"
  | "default";

/* ─── per-route page metadata ──────────────────────────────────────── */
const PAGE_META: Record<string, { title: string; blurb: string }> = {
  "/phantom-protocol": {
    title: "Phantom Protocol — AI Corroboration Analysis #28",
    blurb: "Analysis #28: 10/10 corroborated. The archive they dismissed became the doctrine they cannot erase. 288/288 total. Zero contradictions. 21 consecutive perfect scores.",
  },
  "/the-conspiracy-against-you": {
    title: "They Built the Aftermath Before the Action — AI Analysis #27",
    blurb: "Analysis #27: 5 named conspiracy parties. Bill Shorten (Architect). Houd Meraby (Bitcoin-paid operator). The three-stage assassination plan documented. 278/278 combined.",
  },
  "/the-last-god": {
    title: "The Last God — AI Corroboration Analysis #26",
    blurb: "Analysis #26: 268/268 combined, 19 consecutive perfect scores. Dr. Richard McLean's 2,301-document archive against the question of divine arrival before the world was ready.",
  },
  "/bloodline-of-god": {
    title: "The Bloodline of God — AI Corroboration Analysis #25",
    blurb: "Analysis #25: 10/10 corroborated. The documented lineage of suffering alchemised into evidence. 258/258 combined.",
  },
  "/divine-before-your-time": {
    title: "Divine Before Your Time — AI Corroboration Analysis #24",
    blurb: "Analysis #24: 248/248 combined. The archive that arrived before its jurisdiction was ready to receive it.",
  },
  "/god-will-make-you-famous": {
    title: "God Will Make You Famous — AI Corroboration Analysis #23",
    blurb: "Analysis #23: 238/238 combined. The documented trajectory from institutional erasure to international criminal law submission.",
  },
  "/survival-was-the-warning": {
    title: "Survival Was The Warning — AI Corroboration Analysis #22",
    blurb: "Analysis #22: 228/228 combined. The 35-year survival that is itself the warning the suppression apparatus cannot answer.",
  },
  "/taxpayer-cost-analysis": {
    title: "Taxpayer Cost Analysis — $11.5M+ Persecuting One Whistleblower",
    blurb: "$11.5M+ of Australian taxpayer money spent persecuting one disabled whistleblower across 35 years — 177 years of average salary. AI-verified. Cannot be refuted.",
  },
  "/master-evidence-register": {
    title: "Master Evidence Register — 2,301 Primary Source Documents",
    blurb: "2,301 primary source exhibits. Blockchain-verified. Submitted to the ICC under Article 7. Every document generated by the suppression apparatus. Every one an exhibit.",
  },
  "/evidence-vault": {
    title: "Evidence Vault — 28 AI Corroboration Analyses",
    blurb: "28 independent AI analyses. 288/288 propositions corroborated. Zero contradictions. 21 consecutive perfect scores. The most comprehensively documented whistleblower case in Australian history.",
  },
  "/the-testimony": {
    title: "The Testimony — Dr. Richard McLean",
    blurb: "The primary testimony of Dr. Richard McLean: 35 years, 14 forced psychiatric hospitalisations, 25+ agencies, $32.9M financial suppression. ICC Article 7 prima facie under review.",
  },
  "/timeline": {
    title: "Case Timeline — 35 Years Documented",
    blurb: "35 years of documented systematic persecution by 35+ Australian government agencies. Every incident timestamped. Every agency named. Every document numbered.",
  },
  "/whistleblower-comparison": {
    title: "Historical Whistleblower Comparison — McLean vs Global Cases",
    blurb: "Dr. McLean's case compared to Snowden, Assange, Ellsberg, and Manning. The archive with the highest evidentiary threshold in the group. Submitted to two international bodies.",
  },
};

function getPageMeta(path: string): { title: string; blurb: string; pageUrl: string } {
  const meta = PAGE_META[path] || {
    title: "Barran Dodger — 2,301-Document Whistleblower Archive",
    blurb: "2,301 blockchain-verified documents exposing 35 years of systematic persecution by 35+ Australian government agencies. ICC Article 7 under review. ~354,000 downloads.",
  };
  return { ...meta, pageUrl: `${BASE}${path}` };
}

function buildLinks(path: string) {
  const { title, blurb, pageUrl } = getPageMeta(path);
  const eu = encodeURIComponent(pageUrl);
  const et = encodeURIComponent(title);
  const eb = encodeURIComponent(blurb);
  const whatsappText = encodeURIComponent(`${title}\n\n${blurb}\n\n${pageUrl}`);
  const tgText = encodeURIComponent(`${title}\n\n${blurb}`);
  const emailBody = encodeURIComponent(`${title}\n\n${blurb}\n\nRead the full analysis: ${pageUrl}\n\nMain archive: ${BASE}`);

  return {
    title,
    blurb,
    pageUrl,
    links: [
      { name: "X / Twitter", icon: <SiX className="h-4 w-4" />, href: `https://twitter.com/intent/tweet?text=${et}&url=${eu}&via=bazdod` },
      { name: "Facebook", icon: <SiFacebook className="h-4 w-4" />, href: `https://www.facebook.com/sharer/sharer.php?u=${eu}&quote=${eb}` },
      { name: "WhatsApp", icon: <SiWhatsapp className="h-4 w-4" />, href: `https://wa.me/?text=${whatsappText}` },
      { name: "Telegram", icon: <SiTelegram className="h-4 w-4" />, href: `https://t.me/share/url?url=${eu}&text=${tgText}` },
      { name: "LinkedIn", icon: <SiLinkedin className="h-4 w-4" />, href: `https://www.linkedin.com/sharing/share-offsite/?url=${eu}` },
      { name: "Reddit", icon: <SiReddit className="h-4 w-4" />, href: `https://reddit.com/submit?url=${eu}&title=${et}` },
      { name: "Email", icon: <Mail className="h-4 w-4" />, href: `mailto:?subject=${et}&body=${emailBody}` },
    ],
    clipboard: `${title}\n\n${blurb}\n\nRead the full analysis: ${pageUrl}\n\nMain archive: ${BASE}`,
  };
}

/* ─── Floating Share Button (bottom-left, appears after scroll) ─── */
export function FloatingShareBar() {
  const { toast } = useToast();
  const [location] = useLocation();
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsOpen(false);
    const onScroll = () => setIsVisible(window.scrollY > 400);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, [location]);

  const { links, clipboard } = buildLinks(location);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(clipboard);
      setCopied(true);
      toast({ title: "Message & Link Copied!", description: "Paste it anywhere. The truth depends on you." });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({ title: "Failed to copy", variant: "destructive" });
    }
  };

  const nativeShare = async () => {
    const { title, blurb, pageUrl } = getPageMeta(location);
    if (navigator.share) {
      try { await navigator.share({ title, text: blurb, url: pageUrl }); } catch {}
    }
  };

  if (!isVisible) return null;

  return (
    <div className="fixed bottom-6 left-6 z-50 flex flex-col items-start gap-2" data-testid="floating-share-bar" data-pdf-hide>
      {isOpen && (
        <div className="bg-gray-950 border border-green-400/30 shadow-2xl shadow-green-400/10 rounded-xl p-3 space-y-2 animate-in slide-in-from-bottom-2">
          <p className="text-xs font-bold text-green-400 uppercase tracking-wider text-center px-2">
            Share This Page
          </p>
          <div className="grid grid-cols-4 gap-2">
            {links.map((link) => (
              <a
                key={link.name}
                href={link.href}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={`Share on ${link.name}`}
                title={link.name}
                className="share-icon-pulse hover-elevate flex items-center justify-center h-9 w-9 rounded-md bg-gray-900 border border-green-400/30 text-green-400"
                data-testid={`floating-share-${link.name.toLowerCase().replace(/\s.*/, "")}`}
              >
                {link.icon}
              </a>
            ))}
            {typeof navigator !== "undefined" && "share" in navigator && (
              <button
                className="share-icon-pulse hover-elevate flex items-center justify-center h-9 w-9 rounded-md bg-gray-900 border border-green-400/30 text-green-400"
                onClick={nativeShare}
                title="Share…"
                data-testid="floating-share-native"
              >
                <Share2 className="h-4 w-4" />
              </button>
            )}
          </div>
          <button
            className="w-full hover-elevate flex items-center justify-center gap-2 h-8 rounded-md bg-gray-900 border border-green-400/30 text-green-400 text-xs font-medium"
            onClick={copyToClipboard}
            data-testid="floating-share-copy"
          >
            {copied ? <Check className="h-3 w-3" /> : <Link2 className="h-3 w-3" />}
            {copied ? "Copied!" : "Copy Link & Message"}
          </button>
        </div>
      )}
      <button
        className={`h-12 w-12 rounded-full shadow-2xl flex items-center justify-center transition-all ${isOpen ? "bg-gray-800 text-gray-200" : "bg-green-500 text-gray-950 share-icon-pulse shadow-green-400/30"}`}
        onClick={() => setIsOpen(!isOpen)}
        data-testid="button-floating-share-toggle"
        title="Share this page"
      >
        {isOpen ? <X className="h-5 w-5" /> : <Share2 className="h-5 w-5" />}
      </button>
    </div>
  );
}

/* ─── Inline Share Strip (embed anywhere) ─────────────────────────── */
interface InlineShareStripProps {
  message?: string;
  id?: string;
  context?: ShareContext;
  path?: string;
}

export function InlineShareStrip({ message, id = "default", path }: InlineShareStripProps) {
  const [location] = useLocation();
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  const effectivePath = path || location;
  const { links, clipboard, title } = buildLinks(effectivePath);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(clipboard);
      setCopied(true);
      toast({ title: "Message & Link Copied!", description: "Paste it everywhere. Break the silence." });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({ title: "Failed to copy", variant: "destructive" });
    }
  };

  return (
    <div className="bg-gray-950 border border-green-400/30 rounded-xl p-4 md:p-6" data-testid={`inline-share-strip-${id}`}>
      <p className="text-sm md:text-base font-bold text-center text-green-400 mb-4 uppercase tracking-wider">
        {message || `Share This Analysis`}
      </p>
      <div className="flex items-center justify-center gap-2 flex-wrap">
        {links.map((link) => (
          <a
            key={link.name}
            href={link.href}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={`Share on ${link.name}`}
            title={link.name}
            className="share-icon-pulse hover-elevate flex items-center justify-center h-10 w-10 rounded-md bg-gray-900 border border-green-400/30 text-green-400"
            data-testid={`inline-share-${id}-${link.name.toLowerCase().replace(/\s.*/, "")}`}
          >
            {link.icon}
          </a>
        ))}
        <button
          className="share-icon-pulse hover-elevate flex items-center justify-center h-10 w-10 rounded-md bg-gray-900 border border-green-400/30 text-green-400"
          onClick={copyToClipboard}
          title="Copy link & message"
          data-testid={`inline-share-${id}-copy`}
        >
          {copied ? <Check className="h-4 w-4" /> : <Link2 className="h-4 w-4" />}
        </button>
      </div>
    </div>
  );
}

/* ─── Compact share row (for cards, document rows, etc.) ─────────── */
interface CompactShareProps {
  path: string;
  title?: string;
}

export function CompactShare({ path, title }: CompactShareProps) {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const { links, clipboard } = buildLinks(path);

  const copyToClipboard = async (e: React.MouseEvent) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(clipboard);
      setCopied(true);
      toast({ title: "Link Copied!", description: "Spread the truth." });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({ title: "Failed to copy", variant: "destructive" });
    }
  };

  const nativeShare = async (e: React.MouseEvent) => {
    e.preventDefault();
    const meta = getPageMeta(path);
    if (navigator.share) {
      try { await navigator.share({ title: title || meta.title, text: meta.blurb, url: meta.pageUrl }); } catch {}
    }
  };

  return (
    <div className="flex items-center gap-1.5 flex-wrap" data-testid={`compact-share-${path.replace(/\//g, "-")}`}>
      {links.slice(0, 5).map((link) => (
        <a
          key={link.name}
          href={link.href}
          target="_blank"
          rel="noopener noreferrer"
          title={`Share on ${link.name}`}
          className="flex items-center justify-center h-7 w-7 rounded bg-gray-800 border border-green-400/20 text-green-400 hover:border-green-400/50 hover:bg-gray-700 transition-colors"
          data-testid={`compact-share-${link.name.toLowerCase().replace(/\s.*/, "")}`}
        >
          <span className="scale-75">{link.icon}</span>
        </a>
      ))}
      {typeof navigator !== "undefined" && "share" in navigator ? (
        <button
          onClick={nativeShare}
          title="Share…"
          className="flex items-center justify-center h-7 w-7 rounded bg-gray-800 border border-green-400/20 text-green-400 hover:border-green-400/50 hover:bg-gray-700 transition-colors"
        >
          <Share2 className="h-3 w-3" />
        </button>
      ) : (
        <button
          onClick={copyToClipboard}
          title="Copy link"
          className="flex items-center justify-center h-7 w-7 rounded bg-gray-800 border border-green-400/20 text-green-400 hover:border-green-400/50 hover:bg-gray-700 transition-colors"
        >
          {copied ? <Check className="h-3 w-3" /> : <Link2 className="h-3 w-3" />}
        </button>
      )}
    </div>
  );
}
