import { useState } from "react";
import { useLocation } from "wouter";
import { Share2, Link2, Check, Mail } from "lucide-react";
import { SiX, SiFacebook, SiLinkedin, SiReddit, SiWhatsapp, SiTelegram } from "react-icons/si";
import { useToast } from "@/hooks/use-toast";

const BASE = "https://www.barrandodger.com";

const PAGE_META: Record<string, { title: string; blurb: string }> = {
  "/phantom-protocol": {
    title: "Phantom Protocol — AI Corroboration Analysis #28",
    blurb: "10/10 corroborated. 288/288 total propositions verified across 28 analyses. Zero contradictions. 21 consecutive perfect scores. Dr. Richard McLean's 2,301-document archive vs. AI impartial analysis.",
  },
  "/the-conspiracy-against-you": {
    title: "They Built the Aftermath Before the Action — Analysis #27",
    blurb: "10/10 corroborated. Named parties: Bill Shorten (Architect), Houd Meraby (Bitcoin-paid operator), Sukhi Tear (financial exile coordinator), Tony Riddle & Steve Iasonidis (infiltrators). 278/278 combined.",
  },
  "/the-last-god": {
    title: "The Last God — AI Corroboration Analysis #26",
    blurb: "10/10 corroborated. 268/268 combined. 19 consecutive perfect scores. The archive of divine arrival before the world was ready. Dr. Richard McLean — barrandodger.com",
  },
  "/bloodline-of-god": {
    title: "The Bloodline of God — AI Corroboration Analysis #25",
    blurb: "10/10 corroborated. 258/258 combined. The documented lineage of suffering alchemised into evidence. Dr. Richard McLean — barrandodger.com",
  },
  "/divine-before-your-time": {
    title: "Divine Before Your Time — AI Corroboration Analysis #24",
    blurb: "10/10 corroborated. 248/248 combined. The archive that arrived before its jurisdiction was ready. Dr. Richard McLean — barrandodger.com",
  },
  "/god-will-make-you-famous": {
    title: "God Will Make You Famous — AI Corroboration Analysis #23",
    blurb: "10/10 corroborated. 238/238 combined. From institutional erasure to international criminal law. Dr. Richard McLean — barrandodger.com",
  },
  "/survival-was-the-warning": {
    title: "Survival Was The Warning — AI Corroboration Analysis #22",
    blurb: "10/10 corroborated. 228/228 combined. 35 years of documented survival as its own evidence. Dr. Richard McLean — barrandodger.com",
  },
  "/chosen-ones-perfect-trap": {
    title: "The Chosen One's Perfect Trap — AI Corroboration Analysis #1",
    blurb: "The analysis that started it all. Every institutional failure documented. Every trap baited and recorded. Dr. Richard McLean — barrandodger.com",
  },
  "/taxpayer-cost-analysis": {
    title: "Taxpayer Cost Analysis — $11.5M+ Persecuting One Whistleblower",
    blurb: "AI-calculated: $11.5M+ of Australian taxpayer money spent persecuting a single disabled whistleblower across 35 years. 177 years of average salary. Every dollar documented. Cannot be refuted.",
  },
  "/master-evidence-register": {
    title: "Master Evidence Register — 2,301 Primary Source Documents",
    blurb: "2,301 primary source exhibits. Blockchain-verified. Submitted to the ICC under Article 7. Every document generated by the suppression apparatus has become an exhibit against it.",
  },
  "/master-forensic-evidence-report": {
    title: "Master Forensic Evidence Report — Dr. Richard McLean",
    blurb: "The definitive forensic summary. 35 agencies. 35 years. 2,301 documents. ICC Article 7 prima facie established. Blockchain-sealed. barrandodger.com",
  },
  "/whistleblower-comparison": {
    title: "Whistleblower Comparison — McLean vs Global Cases",
    blurb: "Dr. McLean's case vs Snowden, Assange, Ellsberg & Manning. Highest evidentiary threshold in the group. Two international body submissions. barrandodger.com",
  },
  "/the-full-pattern": {
    title: "The Full Pattern — AI Forensic Analysis",
    blurb: "The complete pattern of systemic persecution documented by AI forensic analysis. Every agency. Every incident. Every connection. Dr. Richard McLean — barrandodger.com",
  },
  "/manifesto": {
    title: "The McLean Manifesto — A Declaration Against Institutional Corruption",
    blurb: "A formal declaration against 35 years of systematic persecution by 35+ Australian government agencies. 2,301 documents back every word. barrandodger.com",
  },
  "/letter-to-the-world": {
    title: "Letter to the World — Dr. Richard McLean",
    blurb: "An open letter addressed to the world from a man the Australian government spent $11.5M+ attempting to silence. barrandodger.com",
  },
  "/apotheosis": {
    title: "Apotheosis Statement — Dr. Richard McLean",
    blurb: "The apotheosis: from targeted individual to international evidentiary record. Dr. Richard McLean — barrandodger.com",
  },
  "/ai-justice-statement": {
    title: "AI Justice Statement — Impartial Verdict",
    blurb: "What happens when AI is asked to assess 35 years of documented persecution with no political agenda? The verdict cannot be ignored. barrandodger.com",
  },
  "/administrative-annihilation": {
    title: "Administrative Annihilation — The Bureaucratic Weapon",
    blurb: "How 35+ government agencies weaponised bureaucratic process to destroy a whistleblower from the inside. Every document. Every denial. Every strategy exposed. barrandodger.com",
  },
  "/legal-status": {
    title: "Legal Status — ICC & UNHCR Submissions",
    blurb: "Current legal status of submissions to the International Criminal Court under Article 7 and the UNHCR. The case that cannot be made to disappear. barrandodger.com",
  },
  "/timeline": {
    title: "Case Timeline — 35 Years of Documented Persecution",
    blurb: "35 years of documented systematic persecution. Every incident timestamped. Every agency named. Every document numbered. barrandodger.com",
  },
};

const EXCLUDED = new Set([
  "/",
  "/store",
  "/donate",
  "/contact",
  "/visitors",
  "/spread-the-truth",
  "/video-commentary",
  "/the-truth",
  "/blockchain",
  "/archive",
  "/start-here",
  "/mission",
  "/research",
  "/evidence",
  "/prophetic-papers",
  "/gospel",
  "/church",
  "/media",
  "/publications",
  "/retrospective-statement",
  "/case-studies",
  "/josephs-coat",
  "/evidence-vault",
]);

function getShareData(path: string) {
  const meta = PAGE_META[path] || {
    title: "Barran Dodger — 2,301-Document Whistleblower Archive",
    blurb: "2,301 blockchain-verified documents. 28 AI corroboration analyses. 288/288 propositions verified. Zero contradictions. ICC Article 7 under review. ~354,000 downloads.",
  };
  const pageUrl = `${BASE}${path}`;
  const eu = encodeURIComponent(pageUrl);
  const et = encodeURIComponent(meta.title);
  const eb = encodeURIComponent(meta.blurb);
  const waText = encodeURIComponent(`${meta.title}\n\n${meta.blurb}\n\n${pageUrl}`);
  const tgText = encodeURIComponent(`${meta.title}\n\n${meta.blurb}`);
  const emailBody = encodeURIComponent(`${meta.title}\n\n${meta.blurb}\n\nRead the full analysis:\n${pageUrl}\n\nMain archive: ${BASE}`);

  return {
    ...meta,
    pageUrl,
    clipboard: `${meta.title}\n\n${meta.blurb}\n\nRead the full analysis:\n${pageUrl}\n\nMain archive: ${BASE}`,
    links: [
      { name: "X / Twitter", short: "X", icon: <SiX className="h-4 w-4" />, href: `https://twitter.com/intent/tweet?text=${et}&url=${eu}&via=bazdod` },
      { name: "Facebook", short: "Facebook", icon: <SiFacebook className="h-4 w-4" />, href: `https://www.facebook.com/sharer/sharer.php?u=${eu}&quote=${eb}` },
      { name: "WhatsApp", short: "WhatsApp", icon: <SiWhatsapp className="h-4 w-4" />, href: `https://wa.me/?text=${waText}` },
      { name: "Telegram", short: "Telegram", icon: <SiTelegram className="h-4 w-4" />, href: `https://t.me/share/url?url=${eu}&text=${tgText}` },
      { name: "LinkedIn", short: "LinkedIn", icon: <SiLinkedin className="h-4 w-4" />, href: `https://www.linkedin.com/sharing/share-offsite/?url=${eu}` },
      { name: "Reddit", short: "Reddit", icon: <SiReddit className="h-4 w-4" />, href: `https://reddit.com/submit?url=${eu}&title=${et}` },
      { name: "Email", short: "Email", icon: <Mail className="h-4 w-4" />, href: `mailto:?subject=${et}&body=${emailBody}` },
    ],
  };
}

export function GlobalAnalysisShareStrip() {
  const [location] = useLocation();
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  if (EXCLUDED.has(location)) return null;

  const { title, blurb, links, clipboard, pageUrl } = getShareData(location);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(clipboard);
      setCopied(true);
      toast({ title: "Link & Message Copied!", description: "Paste it everywhere. The truth needs witnesses." });
      setTimeout(() => setCopied(false), 2500);
    } catch {
      toast({ title: "Failed to copy", variant: "destructive" });
    }
  };

  const nativeShare = async () => {
    if (navigator.share) {
      try { await navigator.share({ title, text: blurb, url: pageUrl }); } catch {}
    }
  };

  return (
    <div className="border-t border-green-400/20 bg-gray-950/80 backdrop-blur-sm mt-16 py-10 px-4" data-testid="global-analysis-share-strip" data-pdf-hide>
      <div className="max-w-3xl mx-auto text-center space-y-5">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-green-400 mb-1">Spread This Evidence</p>
          <p className="text-sm text-gray-400 max-w-xl mx-auto">
            Every share is a record the suppression apparatus cannot erase. Share this page directly to your network.
          </p>
        </div>

        <div className="flex items-center justify-center gap-2 flex-wrap">
          {links.map((link) => (
            <a
              key={link.name}
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`Share on ${link.name}`}
              title={link.name}
              className="flex items-center gap-2 h-10 px-3 rounded-lg bg-gray-900 border border-green-400/25 text-green-400 text-sm font-medium hover:border-green-400/60 hover:bg-gray-800 transition-colors"
              data-testid={`global-share-${link.short.toLowerCase()}`}
            >
              {link.icon}
              <span className="hidden sm:inline">{link.short}</span>
            </a>
          ))}

          <button
            onClick={copyToClipboard}
            title="Copy link & message"
            className="flex items-center gap-2 h-10 px-3 rounded-lg bg-gray-900 border border-green-400/25 text-green-400 text-sm font-medium hover:border-green-400/60 hover:bg-gray-800 transition-colors"
            data-testid="global-share-copy"
          >
            {copied ? <Check className="h-4 w-4" /> : <Link2 className="h-4 w-4" />}
            <span className="hidden sm:inline">{copied ? "Copied!" : "Copy Link"}</span>
          </button>

          {typeof navigator !== "undefined" && "share" in navigator && (
            <button
              onClick={nativeShare}
              title="Share via system dialog"
              className="flex items-center gap-2 h-10 px-3 rounded-lg bg-green-500/10 border border-green-500/40 text-green-400 text-sm font-medium hover:bg-green-500/20 transition-colors"
              data-testid="global-share-native"
            >
              <Share2 className="h-4 w-4" />
              <span className="hidden sm:inline">Share…</span>
            </button>
          )}
        </div>

        <p className="text-xs text-gray-600 font-mono break-all">{pageUrl}</p>
      </div>
    </div>
  );
}
